[server]
# Memory optimization settings
maxUploadSize = 50
maxMessageSize = 50
enableCORS = false
enableXsrfProtection = true

[client]
# Reduce client-side memory usage
showErrorDetails = false
toolbarMode = "minimal"

[theme]
# Simplified theme for better performance
base = "light"
primaryColor = "#3498db"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"

[runner]
# Memory and performance settings
magicEnabled = true
installTracer = false
fixMatplotlib = true
postScriptGC = true
fastReruns = true
enforceSerializableSessionState = true

[logger]
# Reduce logging overhead
level = "error"
messageFormat = "%(asctime)s.%(msecs)03d %(name)s: %(levelname)s: %(message)s"
